title: 'Pegleraj Irena'
default_lang: en
author:
  name: 'Tomislav Turkalj'
  email: tturka33@gmail.com
taxonomies:
  - peglaonica
  - peglaona
metadata: null
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
email: your-email@domain.com
description: 'Pegleraj Irena. Peglaonica Irena.'
links:
  -
    title: 'O nama'
    url: '#o_nama'
  -
    title: 'Cjenik'
    url: '#cjenik'
  -
    title: 'Kontakt'
    url: '#kontakt'

social:
  -
    title: facebook
    url: 'https://www.facebook.com/Pegleraj-Irena-104472254352082/'
